#pragma kernel CalculateFibonacciSpiral

#define PI 3.14159265

RWStructuredBuffer<float2> buffer;
float theta;
float r;

[numthreads(4, 1, 1)]
void CalculateFibonacciSpiral(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    float rad = theta * dispatchThreadID.x * PI / 180;
    
    buffer[dispatchThreadID.x].x = r * dispatchThreadID.x * cos(rad);
    buffer[dispatchThreadID.x].y = r * dispatchThreadID.x * sin(rad);
}
